/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CreativeAuthApiEndpointsAuthVerifyEmailVerifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreativeAuthApiEndpointsAuthResetPasswordResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreativeAuthApiEndpointsAuthRegisterRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreativeAuthApiEndpointsAuthRefreshTokenRefreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreativeAuthApiEndpointsAuthLogoutLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreativeAuthApiEndpointsAuthLoginLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreativeAuthApiEndpointsAuthForgotPasswordForgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreativeAuthApiEndpointsAuthVerifyEmailVerifyEmailResponse: {
            Message?: string;
        };
        CreativeAuthApiEndpointsAuthVerifyEmailVerifyEmailRequest: Record<string, never>;
        CreativeAuthApiEndpointsAuthResetPasswordResetPasswordRequest: {
            Token?: string;
            NewPassword?: string;
        };
        CreativeAuthApiEndpointsAuthRegisterRegisterResponse: {
            Message?: string;
        };
        CreativeAuthApiEndpointsAuthRegisterRegisterRequest: {
            Email?: string;
            Password?: string;
            FirstName?: string;
            LastName?: string;
        };
        CreativeAuthApplicationFeaturesLoginAuthResponse: {
            Token?: string;
            RefreshToken?: string;
            /** Format: date-time */
            RefreshTokenExpiration?: string;
            Email?: string;
        };
        CreativeAuthApiEndpointsAuthRefreshTokenRefreshTokenRequest: {
            Token?: string;
        };
        CreativeAuthApiEndpointsAuthLogoutLogoutRequest: {
            RefreshToken?: string;
        };
        CreativeAuthApplicationFeaturesLoginLoginRequest: {
            Email?: string;
            Password?: string;
        };
        CreativeAuthApiEndpointsAuthForgotPasswordForgotPasswordResponse: {
            Message?: string;
        };
        CreativeAuthApiEndpointsAuthForgotPasswordForgotPasswordRequest: {
            Email?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CreativeAuthApiEndpointsAuthVerifyEmailVerifyEmail: {
        parameters: {
            query: {
                Token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeAuthApiEndpointsAuthVerifyEmailVerifyEmailResponse"];
                };
            };
        };
    };
    CreativeAuthApiEndpointsAuthResetPasswordResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreativeAuthApiEndpointsAuthResetPasswordResetPasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreativeAuthApiEndpointsAuthRegisterRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreativeAuthApiEndpointsAuthRegisterRegisterRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeAuthApiEndpointsAuthRegisterRegisterResponse"];
                };
            };
        };
    };
    CreativeAuthApiEndpointsAuthRefreshTokenRefreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreativeAuthApiEndpointsAuthRefreshTokenRefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeAuthApplicationFeaturesLoginAuthResponse"];
                };
            };
        };
    };
    CreativeAuthApiEndpointsAuthLogoutLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreativeAuthApiEndpointsAuthLogoutLogoutRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreativeAuthApiEndpointsAuthLoginLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreativeAuthApplicationFeaturesLoginLoginRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeAuthApplicationFeaturesLoginAuthResponse"];
                };
            };
        };
    };
    CreativeAuthApiEndpointsAuthForgotPasswordForgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreativeAuthApiEndpointsAuthForgotPasswordForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeAuthApiEndpointsAuthForgotPasswordForgotPasswordResponse"];
                };
            };
        };
    };
}
