/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { AuthService } from "./AuthService";
import { authService } from "./AuthService";
export type Services = {
    auth: AuthService;
};
export const services: {
    auth: typeof authService;
} = {
    auth: authService
};
